name: PanicButton
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "16.0"
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [iosApp/iosApp]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.panicbutton
      FRAMEWORK_SEARCH_PATHS: $(inherited) "$(SRCROOT)/composeApp/build/bin/iosSimulatorArm64/releaseFramework"
      ONLY_ACTIVE_ARCH: "YES"
      ARCHS: "arm64"
      CODE_SIGNING_ALLOWED: "NO"
      CODE_SIGNING_REQUIRED: "NO"
    dependencies:
      - framework: composeApp/build/bin/iosSimulatorArm64/releaseFramework/ComposeApp.framework
        embed: true
